/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_kghost_android_openvpn_OpenVpn_ControlChannel */

#ifndef _Included_info_kghost_android_openvpn_OpenVpn_ControlChannel
#define _Included_info_kghost_android_openvpn_OpenVpn_ControlChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_kghost_android_openvpn_OpenVpn_ControlChannel
 * Method:    recv
 * Signature: (Linfo/kghost/android/openvpn/FileDescriptorHolder;Ljava/nio/Buffer;IILinfo/kghost/android/openvpn/FileDescriptorHolder;)I
 */
JNIEXPORT jint JNICALL Java_info_kghost_android_openvpn_OpenVpn_00024ControlChannel_recv
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jobject);

/*
 * Class:     info_kghost_android_openvpn_OpenVpn_ControlChannel
 * Method:    send
 * Signature: (Linfo/kghost/android/openvpn/FileDescriptorHolder;Ljava/nio/Buffer;II)I
 */
JNIEXPORT jint JNICALL Java_info_kghost_android_openvpn_OpenVpn_00024ControlChannel_send__Linfo_kghost_android_openvpn_FileDescriptorHolder_2Ljava_nio_Buffer_2II
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     info_kghost_android_openvpn_OpenVpn_ControlChannel
 * Method:    send
 * Signature: (Linfo/kghost/android/openvpn/FileDescriptorHolder;Ljava/nio/Buffer;IILinfo/kghost/android/openvpn/FileDescriptorHolder;)I
 */
JNIEXPORT jint JNICALL Java_info_kghost_android_openvpn_OpenVpn_00024ControlChannel_send__Linfo_kghost_android_openvpn_FileDescriptorHolder_2Ljava_nio_Buffer_2IILinfo_kghost_android_openvpn_FileDescriptorHolder_2
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
