/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_kghost_android_openvpn_OpenVpn */

#ifndef _Included_info_kghost_android_openvpn_OpenVpn
#define _Included_info_kghost_android_openvpn_OpenVpn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_kghost_android_openvpn_OpenVpn
 * Method:    start
 * Signature: ([Ljava/lang/String;Linfo/kghost/android/openvpn/FileDescriptorHolder;)I
 */
JNIEXPORT jint JNICALL Java_info_kghost_android_openvpn_OpenVpn_start
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     info_kghost_android_openvpn_OpenVpn
 * Method:    stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_openvpn_OpenVpn_stop
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
