/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_kghost_android_openvpn_FileDescriptorHolder */

#ifndef _Included_info_kghost_android_openvpn_FileDescriptorHolder
#define _Included_info_kghost_android_openvpn_FileDescriptorHolder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_kghost_android_openvpn_FileDescriptorHolder
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_openvpn_FileDescriptorHolder_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
